-- Limpieza de estaciones

UPDATE afluencia_metro
SET estacion = CASE estacion
  WHEN 'AgriÂ­cola Oriental' THEN 'Agricola Oriental'
  WHEN 'Boulevard Puerto Aoreo' THEN 'Boulevard Puerto Aereo'
  WHEN 'Centro Modico' THEN 'Centro Medico'
  WHEN 'Deportivo OceaniÂ­a' THEN 'Deportivo Oceania'
  WHEN 'EtiopiÂ­a/Plaza de la Transparencia' THEN 'Etiopia/Plaza de la Transparencia'
  WHEN 'FerreriÂ­a/Arena Ciudad de Moxico' THEN 'Ferreria/Arena Ciudad de Mexico'
  WHEN 'Gomez FariÂ­as' THEN 'Gomez Farias'
  WHEN 'La Villa/BasiÂ­lica' THEN 'La Villa/Basilica'
  WHEN 'NiÃ±os Horoes' THEN 'Ninos Heroes'
  WHEN 'OceaniÂ­a' THEN 'Oceania'
  WHEN 'OliÂ­mpica' THEN 'Olimpica'
  WHEN 'PeÃ±on Viejo' THEN 'Penon Viejo'
  WHEN 'Periforico Oriente' THEN 'Periferico Oriente'
  WHEN 'RiÂ­o de los Remedios' THEN 'Rio de los Remedios'
  WHEN 'San Andros Tomatlan' THEN 'San Andres Tomatlan'
  WHEN 'San JoaquiÂ­n' THEN 'San Joaquin'
  WHEN 'TasqueÃ±a' THEN 'Tasqueña'
  WHEN 'Terminal Aorea' THEN 'Terminal Aerea'
  WHEN 'Villa de Cortos' THEN 'Villa de Cortes'
  WHEN 'Martin Cabrera' THEN 'Martin Carrera'
  WHEN '%Refineri%' THEN 'Refineria'
  WHEN 'Tasqueña' THEN 'Tasquena'
  ELSE estacion
END;

--Agregar estaciones a zona :

UPDATE afluencia_metro SET zona = CASE
    WHEN estacion = 'Acatitla' THEN 'oriente'
    WHEN estacion = 'Aculco' THEN 'oriente'
    WHEN estacion = 'Agricola Oriental' THEN 'oriente'
    WHEN estacion = 'Allende' THEN 'centro'
    WHEN estacion = 'Apatlaco' THEN 'oriente'
    WHEN estacion = 'Aquiles Serdan' THEN 'poniente'
    WHEN estacion = 'Aragon' THEN 'oriente'
    WHEN estacion = 'Atlalilco' THEN 'oriente'
    WHEN estacion = 'Auditorio' THEN 'poniente'
    WHEN estacion = 'Autobuses del Norte' THEN 'norte'
    WHEN estacion = 'Balbuena' THEN 'oriente'
    WHEN estacion = 'Balderas' THEN 'centro'
    WHEN estacion = 'Barranca del Muerto' THEN 'poniente'
    WHEN estacion = 'Bellas Artes' THEN 'centro'
    WHEN estacion = 'Bondojito' THEN 'norte'
    WHEN estacion = 'Bosque de Aragon' THEN 'oriente'
    WHEN estacion = 'Boulevard Puerto Aereo' THEN 'oriente'
    WHEN estacion = 'Buenavista' THEN 'centro'
    WHEN estacion = 'Calle 11' THEN 'oriente'
    WHEN estacion = 'Camarones' THEN 'poniente'
    WHEN estacion = 'Canal de San Juan' THEN 'oriente'
    WHEN estacion = 'Canal del Norte' THEN 'centro'
    WHEN estacion = 'Candelaria' THEN 'centro'
    WHEN estacion = 'Centro Medico' THEN 'centro'
    WHEN estacion = 'Cerro de la Estrella' THEN 'oriente'
    WHEN estacion = 'Chabacano' THEN 'centro'
    WHEN estacion = 'Chapultepec' THEN 'poniente'
    WHEN estacion = 'Chilpancingo' THEN 'centro'
    WHEN estacion = 'Ciudad Azteca' THEN 'oriente'
    WHEN estacion = 'Ciudad Deportiva' THEN 'oriente'
    WHEN estacion = 'Colegio Militar' THEN 'poniente'
    WHEN estacion = 'Constitucion de 1917' THEN 'oriente'
    WHEN estacion = 'Constituyentes' THEN 'poniente'
    WHEN estacion = 'Consulado' THEN 'norte'
    WHEN estacion = 'Copilco' THEN 'sur'
    WHEN estacion = 'Coyoacan' THEN 'sur'
    WHEN estacion = 'Coyuya' THEN 'oriente'
    WHEN estacion = 'Cuatro Caminos' THEN 'poniente'
    WHEN estacion = 'Cuauhtemoc' THEN 'centro'
    WHEN estacion = 'Cuitlahuac' THEN 'poniente'
    WHEN estacion = 'Culhuacan' THEN 'oriente'
    WHEN estacion = 'Deportivo 18 de Marzo' THEN 'norte'
    WHEN estacion = 'Deportivo Oceania' THEN 'oriente'
    WHEN estacion = 'Division del Norte' THEN 'sur'
    WHEN estacion = 'Doctores' THEN 'centro'
    WHEN estacion = 'Ecatepec' THEN 'oriente'
    WHEN estacion = 'Eduardo Molina' THEN 'norte'
    WHEN estacion = 'Eje Central' THEN 'centro'
    WHEN estacion = 'El Rosario' THEN 'poniente'
    WHEN estacion = 'Ermita' THEN 'oriente'
    WHEN estacion = 'Escuadron 201' THEN 'oriente'
    WHEN estacion = 'Etiopia/Plaza de la Transparencia' THEN 'centro'
    WHEN estacion = 'Eugenia' THEN 'sur'
    WHEN estacion = 'Ferreria/Arena Ciudad de Mexico' THEN 'poniente'
    WHEN estacion = 'Fray Servando' THEN 'centro'
    WHEN estacion = 'Garibaldi/Lagunilla' THEN 'centro'
    WHEN estacion = 'General Anaya' THEN 'sur'
    WHEN estacion = 'Gomez Farias' THEN 'oriente'
    WHEN estacion = 'Guelatao' THEN 'oriente'
    WHEN estacion = 'Guerrero' THEN 'centro'
    WHEN estacion = 'Hangares' THEN 'oriente'
    WHEN estacion = 'Hidalgo' THEN 'centro'
    WHEN estacion = 'Hospital 20 de Noviembre' THEN 'sur'
    WHEN estacion = 'Hospital General' THEN 'centro'
    WHEN estacion = 'Impulsora' THEN 'oriente'
    WHEN estacion = 'Indios Verdes' THEN 'norte'
    WHEN estacion = 'Instituto del Petroleo' THEN 'norte'
    WHEN estacion = 'Insurgentes' THEN 'centro'
    WHEN estacion = 'Insurgentes Sur' THEN 'sur'
    WHEN estacion = 'Isabel la Catolica' THEN 'centro'
    WHEN estacion = 'Iztacalco' THEN 'oriente'
    WHEN estacion = 'Iztapalapa' THEN 'oriente'
    WHEN estacion = 'Jamaica' THEN 'oriente'
    WHEN estacion = 'Juanacatlan' THEN 'poniente'
    WHEN estacion = 'Juarez' THEN 'centro'
    WHEN estacion = 'La Paz' THEN 'oriente'
    WHEN estacion = 'La Raza' THEN 'norte'
    WHEN estacion = 'La Viga' THEN 'oriente'
    WHEN estacion = 'La Villa/Basilica' THEN 'norte'
    WHEN estacion = 'Lagunilla' THEN 'centro'
    WHEN estacion = 'Lazaro Cardenas' THEN 'centro'
    WHEN estacion = 'Lindavista' THEN 'norte'
    WHEN estacion = 'Lomas Estrella' THEN 'oriente'
    WHEN estacion = 'Los Reyes' THEN 'oriente'
    WHEN estacion = 'Martin Carrera' THEN 'norte'
    WHEN estacion = 'Merced' THEN 'centro'
    WHEN estacion = 'Mexicaltzingo' THEN 'oriente'
    WHEN estacion = 'Miguel Angel de Quevedo' THEN 'sur'
    WHEN estacion = 'Misterios' THEN 'norte'
    WHEN estacion = 'Mixcoac' THEN 'poniente'
    WHEN estacion = 'Mixiuhca' THEN 'oriente'
    WHEN estacion = 'Moctezuma' THEN 'oriente'
    WHEN estacion = 'Morelos' THEN 'centro'
    WHEN estacion = 'Muzquiz' THEN 'oriente'
    WHEN estacion = 'Nativitas' THEN 'sur'
    WHEN estacion = 'Nezahualcoyotl' THEN 'oriente'
    WHEN estacion = 'Ninos Heroes' THEN 'centro'
    WHEN estacion = 'Nopalera' THEN 'oriente'
    WHEN estacion = 'Normal' THEN 'poniente'
    WHEN estacion = 'Norte 45' THEN 'norte'
    WHEN estacion = 'Obrera' THEN 'centro'
    WHEN estacion = 'Observatorio' THEN 'poniente'
    WHEN estacion = 'Oceania' THEN 'oriente'
    WHEN estacion = 'Olimpica' THEN 'sur'
    WHEN estacion = 'Olivos' THEN 'oriente'
    WHEN estacion = 'Panteones' THEN 'poniente'
    WHEN estacion = 'Pantitlan' THEN 'oriente'
    WHEN estacion = 'Parque de los Venados' THEN 'sur'
    WHEN estacion = 'Patriotismo' THEN 'poniente'
    WHEN estacion = 'Pen Viejo' THEN 'oriente'
    WHEN estacion = 'Penon Viejo' THEN 'oriente'
    WHEN estacion = 'Periferico Oriente' THEN 'oriente'
    WHEN estacion = 'Pino Suarez' THEN 'centro'
    WHEN estacion = 'Plaza Aragon' THEN 'oriente'
    WHEN estacion = 'Polanco' THEN 'poniente'
    WHEN estacion = 'Politecnico' THEN 'norte'
    WHEN estacion = 'Popotla' THEN 'poniente'
    WHEN estacion = 'Portales' THEN 'sur'
    WHEN estacion = 'Potrero' THEN 'norte'
    WHEN estacion = 'Puebla' THEN 'oriente'
    WHEN estacion = 'Refineria' THEN 'poniente'
    WHEN estacion = 'Revolucion' THEN 'centro'
    WHEN estacion = 'Ricardo Flores Magon' THEN 'norte'
    WHEN estacion = 'Rio de los Remedios' THEN 'oriente'
    WHEN estacion = 'Romero Rubio' THEN 'oriente'
    WHEN estacion = 'Salto del Agua' THEN 'centro'
    WHEN estacion = 'San Andres Tomatlan' THEN 'oriente'
    WHEN estacion = 'San Antonio' THEN 'poniente'
    WHEN estacion = 'San Antonio Abad' THEN 'centro'
    WHEN estacion = 'San Cosme' THEN 'poniente'
    WHEN estacion = 'San Joaquin' THEN 'poniente'
    WHEN estacion = 'San Juan de Letran' THEN 'centro'
    WHEN estacion = 'San Lazaro' THEN 'oriente'
    WHEN estacion = 'San Pedro de los Pinos' THEN 'poniente'
    WHEN estacion = 'Santa Anita' THEN 'oriente'
    WHEN estacion = 'Santa Marta' THEN 'oriente'
    WHEN estacion = 'Sevilla' THEN 'poniente'
    WHEN estacion = 'Tacuba' THEN 'poniente'
    WHEN estacion = 'Tacubaya' THEN 'poniente'
    WHEN estacion = 'Talisman' THEN 'norte'
    WHEN estacion = 'Tasquena' THEN 'poniente'
    WHEN estacion = 'Tepalcates' THEN 'oriente'
    WHEN estacion = 'Tepito' THEN 'centro'
    WHEN estacion = 'Terminal Aerea' THEN 'oriente'
    WHEN estacion = 'Tezonco' THEN 'oriente'
    WHEN estacion = 'Tezozomoc' THEN 'poniente'
    WHEN estacion = 'Tlahuac' THEN 'oriente'
    WHEN estacion = 'Tlaltenco' THEN 'oriente'
    WHEN estacion = 'Tlatelolco' THEN 'centro'
    WHEN estacion = 'UAM-Azcapotzalco' THEN 'poniente'
    WHEN estacion = 'UAM-I' THEN 'oriente'
    WHEN estacion = 'Universidad' THEN 'sur'
    WHEN estacion = 'Valle Gomez' THEN 'centro'
    WHEN estacion = 'Vallejo' THEN 'norte'
    WHEN estacion = 'Velodromo' THEN 'oriente'
    WHEN estacion = 'Viaducto' THEN 'centro'
    WHEN estacion = 'Villa de Aragon' THEN 'oriente'
    WHEN estacion = 'Villa de Cortes' THEN 'sur'
    WHEN estacion = 'Viveros/Derechos Humanos' THEN 'sur'
    WHEN estacion = 'Xola' THEN 'sur'
    WHEN estacion = 'Zapata' THEN 'sur'
    WHEN estacion = 'Zapotitlan' THEN 'oriente'
    WHEN estacion = 'Zaragoza' THEN 'oriente'
    WHEN estacion = 'Zocalo/Tenochtitlan' THEN 'centro'
    ELSE zona

END;


--Eliminar registros duplicados exactos
DELETE FROM afluencia_metro a
USING (
  SELECT MIN(id) AS id_valido
  FROM afluencia_metro
  GROUP BY fecha, linea, estacion, tipo_pago, afluencia
  HAVING COUNT(*) > 1
) b
WHERE a.fecha = (SELECT fecha FROM afluencia_metro WHERE id = b.id_valido)
  AND a.linea = (SELECT linea FROM afluencia_metro WHERE id = b.id_valido)
  AND a.estacion = (SELECT estacion FROM afluencia_metro WHERE id = b.id_valido)
  AND a.tipo_pago = (SELECT tipo_pago FROM afluencia_metro WHERE id = b.id_valido)
  AND a.afluencia = (SELECT afluencia FROM afluencia_metro WHERE id = b.id_valido)
  AND a.id <> b.id_valido;

-- Valores negativos de afluencia, años fuera de rango, o que no coincidan  la columna 'anio' y 'mes' y la fecha real
SELECT *
FROM afluencia_metro
WHERE afluencia < 0
   OR anio < 2000
   OR anio > 2025
   OR anio != EXTRACT(YEAR FROM fecha)
   OR LOWER(TRIM(mes)) != LOWER(TO_CHAR(fecha, 'Month'));
     
;-- Todo bien al parecer 
